# Produção da Extração Vegetal e da Silvicultura
# https://sidra.ibge.gov.br/pesquisa/pevs/tabelas

# Tabela 289 - Quantidade produzida e valor da produção na extração vegetal,
#              por tipo de produto extrativo
[[tabelas]]
sidra_tabela = "289"
variables = ["allxp"]
territories = {6 = []}
unnest_classifications = true

# Tabela 291 - Quantidade produzida e valor da produção na silvicultura,
#              por tipo de produto da silvicultura
[[tabelas]]
sidra_tabela = "291"
variables = ["allxp"]
territories = {6 = []}
unnest_classifications = true
