# Produção Agrícola Municipal - Lavouras Permanentes
# https://sidra.ibge.gov.br/pesquisa/pam/tabelas

# Tabela 1613 - Área colhida, quantidade produzida, rendimento médio e valor da
#               produção das lavouras permanentes
[[tabelas]]
sidra_tabela = "1613"
variables = ["allxp"]
territories = {6 = []}
unnest_classifications = true
