[project]
name = "ibge-sidra-tabelas"
version = "0.1.0"
description = "Tabelas de dados agregados do IBGE"
readme = "README.md"
authors = [
    {name="Daniel Komesu", email="danielkomesu@gmail.com"},
]

requires-python = ">=3.13"

dependencies = [
    "pandas>=2.3.0",
    "psycopg[binary]>=3.2.9",
    "sidrapy>=0.1.4",
    "sqlalchemy>=2.0.41",
]

[tool.black]
line-length = 120

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
