[tool.poetry]
name = "ibge-sidra-tabelas"
version = "0.1.0"
description = "Tabelas de dados agregados do IBGE"
authors = ["Daniel Komesu <danielkomesu@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10"
pandas = "*"
SQLAlchemy = "*"
psycopg2 = "*"
sidrapy = "*"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
