# Pesquisa da Pecuária Municipal - Produção de Origem Animal
# https://sidra.ibge.gov.br/pesquisa/ppm/tabelas

# Tabela 74 - Produção de origem animal, por tipo de produto
[[tabelas]]
sidra_tabela = "74"
variables = ["allxp"]
territories = {6 = []}
unnest_classifications = true

# Tabela 3940 - Produção de origem animal, por tipo de produto (série histórica)
[[tabelas]]
sidra_tabela = "3940"
variables = ["allxp"]
territories = {6 = []}
unnest_classifications = true
