# Sistema Nacional de Índices de Preços ao Consumidor - INPC
# https://sidra.ibge.gov.br/pesquisa/snipc/tabelas

# Tabela 1686 - INPC - Variação mensal (de julho/1989 até dezembro/1990)
[[tabelas]]
sidra_tabela = "1686"
variables = ["44"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {72 = []}

# Tabela 1690 - INPC - Peso mensal (de julho/1989 até dezembro/1990)
[[tabelas]]
sidra_tabela = "1690"
variables = ["45"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {72 = []}

# Tabela 22 - INPC - Variação mensal (de janeiro/1991 até julho/1999)
[[tabelas]]
sidra_tabela = "22"
variables = ["44"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {72 = []}

# Tabela 23 - INPC - Peso mensal (de janeiro/1991 até julho/1999)
[[tabelas]]
sidra_tabela = "23"
variables = ["45"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {72 = []}

# Tabela 653 - INPC - Variação mensal (de agosto/1999 até junho/2006)
[[tabelas]]
sidra_tabela = "653"
variables = ["44"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {315 = []}

# Tabela 654 - INPC - Peso mensal (de agosto/1999 até junho/2006)
[[tabelas]]
sidra_tabela = "654"
variables = ["45"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {315 = []}

# Tabela 2951 - INPC - Variação mensal e peso mensal (de julho/2006 até dezembro/2011)
[[tabelas]]
sidra_tabela = "2951"
variables = ["44", "45"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {315 = []}

# Tabela 1100 - INPC - Variação e peso mensal (de janeiro/2012 até dezembro/2019)
[[tabelas]]
sidra_tabela = "1100"
variables = ["44", "45"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {315 = []}

# Tabela 7063 - INPC - Variação e peso mensal (a partir de janeiro/2020)
[[tabelas]]
sidra_tabela = "7063"
variables = ["44", "45"]
territories = {1 = [], 6 = [], 7 = [], 71 = []}
classifications = {315 = []}
