# Pesquisa da Pecuária Municipal - Aquicultura e Exploração
# https://sidra.ibge.gov.br/pesquisa/ppm/tabelas

# Tabela 94 - Aquicultura - Quantidade produzida e valor da produção,
#             por tipo de produto
[[tabelas]]
sidra_tabela = "94"
variables = ["allxp"]
territories = {6 = []}

# Tabela 95 - Aquicultura - Quantidade de estabelecimentos que praticam
#             aquicultura e área dos tanques/viveiros
[[tabelas]]
sidra_tabela = "95"
variables = ["allxp"]
territories = {6 = []}
