# Produto Interno Bruto dos Municípios
# https://sidra.ibge.gov.br/pesquisa/pib-munic/tabelas

# Tabela 5938 - Produto interno bruto a preços correntes, impostos, líquidos de
#               subsídios, sobre produtos a preços correntes e valor adicionado
#               bruto a preços correntes total e por atividade econômica, e
#               respectivas participações - Referência 2010
[[tabelas]]
sidra_tabela = "5938"
variables = ["37", "498", "513", "517", "525", "543", "6575"]
territories = {6 = ["all"]}
