# Produção Agrícola Municipal - Lavouras Temporárias
# https://sidra.ibge.gov.br/pesquisa/pam/tabelas

# Tabela 839 - Área plantada, área colhida, quantidade produzida e valor da
#              produção das lavouras temporárias
[[tabelas]]
sidra_tabela = "839"
variables = ["allxp"]
territories = {6 = []}
classifications = {81 = ["allxt"]}

# Tabela 1000 - Área plantada ou destinada à colheita das lavouras temporárias
[[tabelas]]
sidra_tabela = "1000"
variables = ["allxp"]
territories = {6 = []}
classifications = {81 = ["allxt"]}

# Tabela 1001 - Área colhida das lavouras temporárias
[[tabelas]]
sidra_tabela = "1001"
variables = ["allxp"]
territories = {6 = []}
classifications = {81 = ["allxt"]}

# Tabela 1002 - Quantidade produzida, rendimento médio da produção, valor da
#               produção das lavouras temporárias
# One request per variable (variables 109, 216, 214, 112)
[[tabelas]]
sidra_tabela = "1002"
variables = ["109", "216", "214", "112"]
split_variables = true
territories = {6 = []}
classifications = {81 = ["allxt"]}

# Tabela 1612 - Área plantada, área colhida, quantidade produzida, rendimento
#               médio e valor da produção das lavouras temporárias
[[tabelas]]
sidra_tabela = "1612"
variables = ["allxp"]
territories = {6 = []}
unnest_classifications = true
