# Censo Demográfico - População
# https://sidra.ibge.gov.br/pesquisa/censo-demografico/series-temporais/series-temporais

# Tabela 200 - População residente, por sexo, situação e grupos de idade -
#              Amostra - Características Gerais da População
[[tabelas]]
sidra_tabela = "200"
variables = ["allxp"]
territories = {6 = ["all"]}
classifications = {2 = ["0"], 1 = ["0"], 58 = ["0"]}

# Tabela 4709 - População residente, Variação absoluta de população residente e Taxa de crescimento geométrico
[[tabelas]]
sidra_tabela = "4709"
variables = ["93"]
territories = {6 = ["all"]}
