# Pesquisa da Pecuária Municipal - Rebanhos
# https://sidra.ibge.gov.br/pesquisa/ppm/tabelas

# Tabela 73 - Efetivo dos rebanhos, por tipo de rebanho
[[tabelas]]
sidra_tabela = "73"
variables = ["allxp"]
territories = {6 = []}
unnest_classifications = true

# Tabela 3939 - Efetivo dos rebanhos, por tipo de rebanho (série histórica)
[[tabelas]]
sidra_tabela = "3939"
variables = ["allxp"]
territories = {6 = []}
unnest_classifications = true
