# Produção da Extração Vegetal e da Silvicultura - Área Florestal
# https://sidra.ibge.gov.br/pesquisa/pevs/tabelas

# Tabela 5930 - Área total dos estabelecimentos agropecuários (ha) com
#               florestas plantadas, por tipo de floresta
[[tabelas]]
sidra_tabela = "5930"
variables = ["allxp"]
territories = {6 = []}
classifications = {734 = ["allxt"]}
