# Sistema Nacional de Índices de Preços ao Consumidor - IPCA
# https://sidra.ibge.gov.br/pesquisa/snipc/tabelas

# Tabela 1692 - IPCA - Variação mensal (de julho/1989 até dezembro/1990)
[[tabelas]]
sidra_tabela = "1692"
variables = ["63"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {72 = []}

# Tabela 1693 - IPCA - Peso mensal (de julho/1989 até dezembro/1990)
[[tabelas]]
sidra_tabela = "1693"
variables = ["66"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {72 = []}

# Tabela 58 - IPCA - Variação mensal (de janeiro/1991 até julho/1999)
[[tabelas]]
sidra_tabela = "58"
variables = ["63"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {72 = []}

# Tabela 61 - IPCA - Peso mensal (de janeiro/1991 até julho/1999)
[[tabelas]]
sidra_tabela = "61"
variables = ["66"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {72 = []}

# Tabela 655 - IPCA - Variação mensal (de agosto/1999 até junho/2006)
[[tabelas]]
sidra_tabela = "655"
variables = ["63"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {315 = []}

# Tabela 656 - IPCA - Peso mensal (de agosto/1999 até junho/2006)
[[tabelas]]
sidra_tabela = "656"
variables = ["66"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {315 = []}

# Tabela 2938 - IPCA - Variação mensal e peso mensal (de julho/2006 até dezembro/2011)
[[tabelas]]
sidra_tabela = "2938"
variables = ["63", "66"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {315 = []}

# Tabela 1419 - IPCA - Variação e peso mensal (de janeiro/2012 até dezembro/2019)
[[tabelas]]
sidra_tabela = "1419"
variables = ["63", "66"]
territories = {1 = [], 6 = [], 7 = []}
classifications = {315 = []}

# Tabela 7060 - IPCA - Variação e peso mensal (a partir de janeiro/2020)
[[tabelas]]
sidra_tabela = "7060"
variables = ["63", "66"]
territories = {1 = [], 6 = [], 7 = [], 71 = []}
classifications = {315 = []}
